#!/bin/sh

# Source the Husky script if it exists
husky_sh_file="$(dirname "$0")/_/husky.sh"
if [ -f "$husky_sh_file" ]; then
    . "$husky_sh_file"
fi

# Unstage all changes that have not been added
git diff --cached --name-only --diff-filter=d | xargs git reset --

# Run pre-commit checks (if any)
yarn pre-commit

# Allow the commit to proceed if no issues
exit 0
